# NumPy Practice

This notebook is to practice with NumPy.


In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

### DataTypes & Attributes
NumPy's main dataype is ndarray (multi dimensional array)

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [3]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6.5]])
print(a2)

[[1.  2.  3. ]
 [4.  5.  6.5]]


In [4]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape: ", a1.shape)
print("Dims: ", a1.ndim)
print("Data Type: ", a1.dtype)
print("Size: ", a1.size)
print("Type: ", type(a1))

Shape:  (3,)
Dims:  1
Data Type:  int64
Size:  3
Type:  <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
print("Shape: ", a2.shape)
print("Dims: ", a2.ndim)
print("Data Type: ", a2.dtype)
print("Size: ", a2.size)
print("Type: ", type(a2))


Shape:  (2, 3)
Dims:  2
Data Type:  float64
Size:  6
Type:  <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
print("Shape: ", a3.shape)
print("Dims: ", a3.ndim)
print("Data Type: ", a3.dtype)
print("Size: ", a3.size)
print("Type: ", type(a3))

Shape:  (2, 2, 3)
Dims:  3
Data Type:  int64
Size:  12
Type:  <class 'numpy.ndarray'>


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,5.0,6.5


In [53]:
# Create an array of shape (10, 2) with only ones
array_ones=np.ones((10,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [54]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros=np.zeros((7,2,3))
print(array_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [55]:
# Create an array within a range of 0 and 100 with step 3
array_range=np.arange(0,100,3)
print(array_range)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [56]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rarray=np.random.randint(0,10,size=(7,2))
print(rarray)

[[2 4]
 [3 5]
 [9 8]
 [6 1]
 [8 6]
 [7 6]
 [9 8]]


In [57]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rarray2=np.random.random((3,5))
print(rarray2)

[[0.84496318 0.13727047 0.51762762 0.91220829 0.04792239]
 [0.77049826 0.20039496 0.23599107 0.39758352 0.54367889]
 [0.92112906 0.94448045 0.29382201 0.21790624 0.90057776]]


In [ ]:
# Set the random seed to 42
np.random.seed(42) # random seed set to 42 ensures reproducibility

# Create a random array of numbers between 0 & 10 of size (4, 6)
rarray3=np.random.randint(0,10,size=(4,6))
print(rarray3)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [71]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rarray4=np.random.randint(1,10,size=(3,7))
print(rarray4)
# Find the unique numbers in the array you just created
np.unique(rarray4)

[[5 2 5 8 9 9 1]
 [9 7 9 8 1 8 8]
 [3 1 8 3 3 1 5]]


array([1, 2, 3, 5, 7, 8, 9], dtype=int32)

In [72]:
# Find the 0'th index of the latest array you created
rarray4[0]

array([5, 2, 5, 8, 9, 9, 1], dtype=int32)

In [74]:
# Get the first 2 rows of latest array you created
rarray4[:2,:]

array([[5, 2, 5, 8, 9, 9, 1],
       [9, 7, 9, 8, 1, 8, 8]], dtype=int32)

In [75]:
# Get the first 2 values of the first 2 rows of the latest array
rarray4[:2,:2]

array([[5, 2],
       [9, 7]], dtype=int32)

In [77]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rarray=np.random.randint(0,10,size=(3,5))
rarray_ones=np.ones((3,5))
print(rarray)
print(rarray_ones)

[[5 2 0 2 4]
 [2 0 4 9 6]
 [6 8 9 9 2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
# Add the two arrays together
rarray + rarray_ones

array([[ 6.,  3.,  1.,  3.,  5.],
       [ 3.,  1.,  5., 10.,  7.],
       [ 7.,  9., 10., 10.,  3.]])

In [79]:
# Create another array of ones of shape (5, 3)
rarray_ones2=np.ones((5,3))

In [81]:
# Try add the array of ones and the other most recent array together
# rarray + rarray_ones2
# Does not workd due to different shapes

In [82]:
# Create another array of ones of shape (3, 5)
rarray5=np.ones((3,5))
rarray5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
# Subtract the new array of ones from the other most recent array
rarray - rarray5

array([[ 4.,  1., -1.,  1.,  3.],
       [ 1., -1.,  3.,  8.,  5.],
       [ 5.,  7.,  8.,  8.,  1.]])

In [84]:
# Multiply the ones array with the latest array
rarray*rarray5

array([[5., 2., 0., 2., 4.],
       [2., 0., 4., 9., 6.],
       [6., 8., 9., 9., 2.]])

In [86]:
# Take the latest array to the power of 2 using '**'
rarray**2

array([[25,  4,  0,  4, 16],
       [ 4,  0, 16, 81, 36],
       [36, 64, 81, 81,  4]], dtype=int32)

In [87]:
# Do the same thing with np.square()
np.square(rarray)

array([[25,  4,  0,  4, 16],
       [ 4,  0, 16, 81, 36],
       [36, 64, 81, 81,  4]], dtype=int32)

In [88]:
# Find the mean of the latest array using np.mean()
np.mean(rarray)

np.float64(4.533333333333333)

In [89]:
# Find the maximum of the latest array using np.max()
np.max(rarray)

np.int32(9)

In [90]:
# Find the minimum of the latest array using np.min()
np.min(rarray)

np.int32(0)

In [91]:
# Find the standard deviation of the latest array
np.std(rarray)

np.float64(3.095516470998373)

In [92]:
# Find the variance of the latest array
np.var(rarray)

np.float64(9.582222222222223)

In [96]:
# Reshape the latest array to (3, 5, 1)
# shape was already (3,5), so we can reshape to (3,5,1)
rarray_reshape = rarray.reshape(3,5,1)
rarray_reshape

array([[[5],
        [2],
        [0],
        [2],
        [4]],

       [[2],
        [0],
        [4],
        [9],
        [6]],

       [[6],
        [8],
        [9],
        [9],
        [2]]], dtype=int32)

In [100]:
# Transpose the latest array
rarray_reshape_transposed=rarray_reshape.T
rarray_reshape_transposed.shape

(1, 5, 3)

In [103]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1=np.random.randint(0,10,size=(3,3))
ar2=np.random.randint(0,10,size=(3,2))
print(ar1)
print(ar2)  

[[5 3 9]
 [6 8 6]
 [0 0 8]]
[[8 3]
 [8 2]
 [6 5]]


In [110]:
# Perform a dot product on the two newest arrays you created
np.dot(ar1,ar2)

array([[118,  66],
       [148,  64],
       [ 48,  40]], dtype=int32)

In [105]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1=np.random.randint(0,10,size=(4,3))
arr2=np.random.randint(0,10,size=(4,3))

In [107]:
# Perform a dot product on the two newest arrays you created
# arr1.dot(arr2)
# Does not work due to shapes not aligned

In [109]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr1.T, arr2)

array([[56, 91, 21],
       [33, 94, 28],
       [54, 73, 30]], dtype=int32)

In [111]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rar1=np.random.randint(0,10,size=(3,4))
rar2=np.random.randint(0,10,size=(3,4))

In [112]:
# Compare the two arrays with '>'
rar1 > rar2

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True,  True, False]])

In [113]:
# Compare the two arrays with '>='
rar1 >= rar2

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [114]:
# Find which elements of the first array are greater than 7
rar1 > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [115]:
# Which parts of each array are equal? (try using '==')
rar1 == rar2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [116]:
# Sort one of the arrays you just created in ascending order
np.sort(rar1)

array([[1, 1, 5, 6],
       [0, 0, 2, 4],
       [1, 4, 5, 9]], dtype=int32)

In [119]:
# Sort the indexes of one of the arrays you just created
print(rar1)
np.argsort(rar1)

[[1 1 5 6]
 [4 0 0 2]
 [1 4 9 5]]


array([[0, 1, 2, 3],
       [1, 2, 3, 0],
       [0, 1, 3, 2]])

In [120]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rar1)

np.int64(10)

In [121]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rar1)

np.int64(5)

In [122]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rar1, axis=1)

array([3, 0, 2])

In [123]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rar1, axis=0)

array([0, 1, 1, 1])

In [ ]:
# Create an array of normally distributed random numbers (BELL CURVE)
rdist=np.random.normal(loc=0.0, scale=1.0, size=(10))
print(rdist)


[-0.3882644  -0.88551237 -0.35674503  0.5561218   1.04386061  0.52644816
  1.36388652  2.53916272 -0.32449096 -0.20586672]


In [132]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr10=np.linspace(1,100,10)
print(arr10)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
